[2023-03-29 16:42:23,434] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:42:21.791298+00:00 [queued]>
[2023-03-29 16:42:23,452] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:42:21.791298+00:00 [queued]>
[2023-03-29 16:42:23,453] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:42:23,454] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:42:23,456] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:42:23,482] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:42:21.791298+00:00
[2023-03-29 16:42:23,488] {standard_task_runner.py:52} INFO - Started process 27725 to run task
[2023-03-29 16:42:23,502] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:42:21.791298+00:00', '--job-id', '410', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpkawsbpa3', '--error-file', '/tmp/tmp34fi91pi']
[2023-03-29 16:42:23,503] {standard_task_runner.py:77} INFO - Job 410: Subtask log_error
[2023-03-29 16:42:23,564] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:42:21.791298+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:42:23,735] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:42:21.791298+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:42:21.791298+00:00
[2023-03-29 16:42:23,738] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:42:23,770] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:42:23,799] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T164221, start_date=20230329T164223, end_date=20230329T164223
[2023-03-29 16:42:23,837] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:42:23,885] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
