[2023-03-29 16:25:29,154] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:25:27.591514+00:00 [queued]>
[2023-03-29 16:25:29,191] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:25:27.591514+00:00 [queued]>
[2023-03-29 16:25:29,192] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:25:29,194] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:25:29,196] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:25:29,247] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:25:27.591514+00:00
[2023-03-29 16:25:29,255] {standard_task_runner.py:52} INFO - Started process 26802 to run task
[2023-03-29 16:25:29,284] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:25:27.591514+00:00', '--job-id', '339', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpp1fi8gbi', '--error-file', '/tmp/tmpflzz81gl']
[2023-03-29 16:25:29,288] {standard_task_runner.py:77} INFO - Job 339: Subtask log_error
[2023-03-29 16:25:29,506] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:25:27.591514+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:25:29,609] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:25:27.591514+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:25:27.591514+00:00
[2023-03-29 16:25:29,611] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:25:29,629] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:25:29,649] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T162527, start_date=20230329T162529, end_date=20230329T162529
[2023-03-29 16:25:29,680] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:25:29,726] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
