[2023-03-29 16:37:35,078] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:37:33.049343+00:00 [queued]>
[2023-03-29 16:37:35,118] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:37:33.049343+00:00 [queued]>
[2023-03-29 16:37:35,119] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:37:35,120] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:37:35,122] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:37:35,169] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:37:33.049343+00:00
[2023-03-29 16:37:35,181] {standard_task_runner.py:52} INFO - Started process 27475 to run task
[2023-03-29 16:37:35,229] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:37:33.049343+00:00', '--job-id', '392', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmphx16bqh_', '--error-file', '/tmp/tmpso38crsu']
[2023-03-29 16:37:35,241] {standard_task_runner.py:77} INFO - Job 392: Subtask log_error
[2023-03-29 16:37:35,392] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:37:33.049343+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:37:35,916] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:37:33.049343+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:37:33.049343+00:00
[2023-03-29 16:37:35,922] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:37:35,988] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:37:36,098] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T163733, start_date=20230329T163735, end_date=20230329T163736
[2023-03-29 16:37:36,232] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:37:36,334] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
