[2023-03-29 16:01:54,691] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:01:52.984278+00:00 [queued]>
[2023-03-29 16:01:54,751] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:01:52.984278+00:00 [queued]>
[2023-03-29 16:01:54,754] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:01:54,756] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:01:54,757] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:01:54,820] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:01:52.984278+00:00
[2023-03-29 16:01:54,845] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:01:52.984278+00:00', '--job-id', '242', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpsit7wo35', '--error-file', '/tmp/tmp6ser8yzf']
[2023-03-29 16:01:54,861] {standard_task_runner.py:77} INFO - Job 242: Subtask log_error
[2023-03-29 16:01:54,839] {standard_task_runner.py:52} INFO - Started process 25529 to run task
[2023-03-29 16:01:54,982] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:01:52.984278+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:01:55,059] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:01:52.984278+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:01:52.984278+00:00
[2023-03-29 16:01:55,062] {ETL.py:66} ERROR - task is NOT completed
[2023-03-29 16:01:55,086] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:01:55,111] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T160152, start_date=20230329T160154, end_date=20230329T160155
[2023-03-29 16:01:55,182] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:01:55,208] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
