[2023-03-29 16:32:41,162] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:32:38.884681+00:00 [queued]>
[2023-03-29 16:32:41,211] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:32:38.884681+00:00 [queued]>
[2023-03-29 16:32:41,212] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:32:41,216] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:32:41,220] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:32:41,259] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:32:38.884681+00:00
[2023-03-29 16:32:41,305] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:32:38.884681+00:00', '--job-id', '369', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpkqroc8lo', '--error-file', '/tmp/tmp3nb24l6f']
[2023-03-29 16:32:41,312] {standard_task_runner.py:77} INFO - Job 369: Subtask log_error
[2023-03-29 16:32:41,281] {standard_task_runner.py:52} INFO - Started process 27198 to run task
[2023-03-29 16:32:41,603] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:32:38.884681+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:32:42,072] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:32:38.884681+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:32:38.884681+00:00
[2023-03-29 16:32:42,077] {ETL.py:70} ERROR - task is NOT completed
[2023-03-29 16:32:42,156] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:32:42,181] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T163238, start_date=20230329T163241, end_date=20230329T163242
[2023-03-29 16:32:42,232] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:32:42,311] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
