[2023-03-29 16:06:18,842] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:06:17.650861+00:00 [queued]>
[2023-03-29 16:06:18,865] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:06:17.650861+00:00 [queued]>
[2023-03-29 16:06:18,867] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:06:18,868] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:06:18,870] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:06:18,894] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:06:17.650861+00:00
[2023-03-29 16:06:18,906] {standard_task_runner.py:52} INFO - Started process 25782 to run task
[2023-03-29 16:06:18,927] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:06:17.650861+00:00', '--job-id', '266', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpx6z8cp9p', '--error-file', '/tmp/tmpagbgl6jm']
[2023-03-29 16:06:18,930] {standard_task_runner.py:77} INFO - Job 266: Subtask log_error
[2023-03-29 16:06:19,054] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:06:17.650861+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:06:19,184] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:06:17.650861+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:06:17.650861+00:00
[2023-03-29 16:06:19,188] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:06:19,213] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:06:19,232] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T160617, start_date=20230329T160618, end_date=20230329T160619
[2023-03-29 16:06:19,304] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:06:19,364] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
