[2023-03-29 16:38:32,232] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:38:30.460418+00:00 [queued]>
[2023-03-29 16:38:32,276] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:38:30.460418+00:00 [queued]>
[2023-03-29 16:38:32,278] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:38:32,279] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-29 16:38:32,280] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:38:32,317] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): log_error> on 2023-03-29T16:38:30.460418+00:00
[2023-03-29 16:38:32,325] {standard_task_runner.py:52} INFO - Started process 27529 to run task
[2023-03-29 16:38:32,338] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_22222222222', 'log_error', '2023-03-29T16:38:30.460418+00:00', '--job-id', '398', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpzl6sle7j', '--error-file', '/tmp/tmpsomow1a6']
[2023-03-29 16:38:32,357] {standard_task_runner.py:77} INFO - Job 398: Subtask log_error
[2023-03-29 16:38:32,441] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_22222222222.log_error 2023-03-29T16:38:30.460418+00:00 [running]> on host 0bc3da97cebb
[2023-03-29 16:38:32,530] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_22222222222
AIRFLOW_CTX_TASK_ID=log_error
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:38:30.460418+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:38:30.460418+00:00
[2023-03-29 16:38:32,533] {ETL.py:67} ERROR - task is NOT completed
[2023-03-29 16:38:32,562] {python.py:151} INFO - Done. Returned value was: None
[2023-03-29 16:38:32,580] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_22222222222, task_id=log_error, execution_date=20230329T163830, start_date=20230329T163832, end_date=20230329T163832
[2023-03-29 16:38:32,621] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-29 16:38:32,656] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
